// Food menus
export const GET_FOODMENUS = 'GET_FOODMENUS';
export const ADD_FOODMENU = 'ADD_FOODMENU';
export const DELETE_FOODMENU = 'DELETE_FOODMENU';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_FOODMENU = 'UPDATE_FOODMENU';
export const FOODMENU_ERROR = 'FOODMENU_ERROR';

// Food orders
export const GET_FOODORDERS = 'GET_FOODORDERS';
export const ADD_FOODORDER = 'ADD_FOODORDER';
export const UPDATE_FOODORDER = 'UPDATE_FOODORDER';
export const CANCEL_FOODORDER = 'CANCEL_FOODORDER';
export const FOODORDER_ERROR = 'FOODORDER_ERROR';
export const CLEAR_FOODORDERS = 'CLEAR_FOODORDERS';
export const FILTER_FOODORDER = 'FILTER_FOODMENU';
export const CLEAR_FILTER = 'CLEAR_FILTER';


// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';